Repository AY2324S1-CS2103-W14-2/tp, pull requests merged in 2023-10, with the labels that each got.

#122 Add usecase
  docs/DeveloperGuide.md
Labels: documentation

#124 Add implementation details for mode feature
  docs/DeveloperGuide.md
Labels: documentation

#126 Fix formatting issue with DG
  docs/DeveloperGuide.md
Labels: bug, documentation

#129 Implement filter by criteria
  docs/UserGuide.md
  docs/index.md
  src/main/java/seedu/address/commons/util/StringUtil.java
  src/main/java/seedu/address/logic/commands/EditMeetingCommand.java
  src/main/java/seedu/address/logic/commands/ListContactCommand.java
  src/main/java/seedu/address/logic/commands/ListMeetingCommand.java
  src/main/java/seedu/address/logic/parser/AddMeetingCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ListContactCommandParser.java
  src/main/java/seedu/address/logic/parser/ListMeetingCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/contact/Contact.java
  src/main/java/seedu/address/model/contact/ContactFilterPredicate.java
  src/main/java/seedu/address/model/contact/Phone.java
  src/main/java/seedu/address/model/meeting/Meeting.java
  src/main/java/seedu/address/model/meeting/MeetingFilterPredicate.java
  src/main/java/seedu/address/model/meeting/Time.java
  src/test/java/seedu/address/logic/commands/ListContactCommandTest.java
  src/test/java/seedu/address/logic/commands/ListMeetingCommandTest.java
  src/test/java/seedu/address/testutil/MeetingBuilder.java
Labels: priority.Medium, type.Epic
