Repository AY2324S1-CS2103-W14-2/tp, pull requests merged in 2023-11, with the labels that each got.

#148 Implement sort for contacts and meetings
  src/main/java/seedu/address/logic/commands/AddContactToMeetingCommand.java
  src/main/java/seedu/address/logic/commands/AddMeetingCommand.java
  src/main/java/seedu/address/logic/commands/ListContactCommand.java
  src/main/java/seedu/address/logic/parser/AddContactToMeetingCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/contact/Contact.java
  src/main/java/seedu/address/model/contact/UniqueContactList.java
  src/main/java/seedu/address/model/meeting/Meeting.java
  src/main/java/seedu/address/model/meeting/MeetingList.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddContactCommandTest.java
  src/test/java/seedu/address/logic/commands/AddMeetingCommandTest.java
  src/test/java/seedu/address/logic/commands/EditContactCommandTest.java
  src/test/java/seedu/address/logic/commands/EditMeetingCommandTest.java
  src/test/java/seedu/address/logic/commands/ListContactCommandTest.java
Labels: priority.Medium

#200 Fix view command feature flaw
  src/main/java/seedu/address/logic/parser/ViewContactCommandParser.java
  src/main/java/seedu/address/logic/parser/ViewMeetingCommandParser.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/ViewContactCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ViewMeetingCommandParserTest.java
Labels: Good To Fix

#223 Fix Bug-Meeting filter not inclusive of input dateTime
  src/main/java/seedu/address/logic/parser/ListMeetingCommandParser.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/contact/Contact.java
  src/main/java/seedu/address/model/meeting/MeetingFilterPredicate.java
  src/test/java/seedu/address/logic/commands/AddContactToMeetingCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteContactCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteContactFromMeetingCommandTest.java
  src/test/java/seedu/address/logic/commands/ListMeetingCommandTest.java
  src/test/java/seedu/address/testutil/MeetingBuilder.java
Labels: bug

#226 Update Documentation
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/AddContactToMeetingActivityDiagram.puml
  docs/diagrams/DeleteContactFromMeetingActivityDiagram.puml
  docs/team/s-peiran.md
Labels: documentation
